### ISSUE TITLE
docs reference wrong version

### ISSUE THREAD

**Issue by magland** [brainsatplay/webnwb#10]
### Description of the bug

https://github.com/brainsatplay/webnwb/blob/541880be37ace8ce70bf107640a29c83c63bcd0b/docs/installation/npm.md?plain=1#L5

1.0.0 should be 0.1.0

### Steps To Reproduce

Go to the docs, installation, npm.

**Comment by garrettmflynn** [comment]
Thanks for flagging this, @magland! Really glad I've got some extra eyes on this project.

Moving forward, let me know if you want to discuss anything in greater detail and I'd be happy to organize something with you.
